# https://docs.travis-ci.com/user/customizing-the-build
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js

matrix:
  include:
    - os: windows
    - os: osx

env:
  - CI=true
node_js:
  - "8"
  - "10"
  - "12"

sudo: false


before_install:
  - npm i -g npm
  - npm cache clean --force

install:
  - npm install
  - npm run bootstrap

before_script:
  - echo before_script

scripts:
  - npm test


notifications:
  email:
    - qiuzhongleiabc@126.com
