# https://docs.travis-ci.com/user/customizing-the-build
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js

env:
  - CI=true

matrix:
  include:
    - os: linux
      node_js: 8
      env: CODECOV=true
    - os: linux
      node_js: 10
    - os: linux
      node_js: 12

    - os: osx
      node_js: 8
    - os: osx
      node_js: 10
    - os: osx
      node_js: 12

    # travis 上的 windows 平台不稳定
    # - os: windows
    #   node_js: 8

# os:
#   - linux
#   - osx
#   - windows
# node_js:
#   - "8"
#   - "10"
#   - "12"

before_install:
  - echo before_install

install:
  - npm install
  - if [ "$CODECOV" = "true" ]; then make cov_install; fi

before_script:
  - echo before_script

scripts:
  - npm test

after_success:
  - if [ "$CODECOV" = "true" ]; then make cov; fi

notifications:
  email:
    - qiuzhongleiabc@126.com
