# https://docs.travis-ci.com/user/customizing-the-build
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js

env:
  - CI=true

matrix:
  include:
    - os: osx
      env: CODECOV=true
    - os: windows

# os:
#   - linux
#   - osx
#   - windows

node_js:
  - "8"
  - "10"
  - "12"

before_install:
  - echo before_install

install:
  - npm install
  - if [ "$CODECOV" = "true" ]; then make cov_install; fi

before_script:
  - echo before_script

scripts:
  - npm test

after_success:
  - if [ "$CODECOV" = "true" ]; then make cov; fi

notifications:
  email:
    - qiuzhongleiabc@126.com
