# https://docs.travis-ci.com/user/customizing-the-build
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js

env:
  - CI=true

matrix:
  include:
    - os: windows
    - os: osx

# os:
#   - linux
#   - osx
#   - windows

node_js:
  - "8"
  - "10"
  - "12"

before_install:
  - echo before_install

install:
  - npm install

before_script:
  - echo before_script

scripts:
  - npm test

notifications:
  email:
    - qiuzhongleiabc@126.com
